# Generated by Django 4.0.3 on 2022-03-25 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divination',
            old_name='name',
            new_name='title',
        ),
    ]
