# Generated by Django 4.0.3 on 2022-03-27 12:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('runes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rune',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
