# Generated by Django 4.0.3 on 2022-03-27 12:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('runes', '0002_alter_rune_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divination',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='rune',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='rune',
            name='forecast_meaning_direct',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='rune',
            name='forecast_meaning_inverted',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
