# Generated by Django 4.0.3 on 2022-03-26 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('runes', '0004_divination_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('forecast_meaning_direct', models.TextField(blank=True)),
                ('forecast_meaning_inverted', models.TextField(blank=True)),
                ('has_inverted', models.BooleanField()),
                ('img_direct', models.URLField()),
                ('img_inverted', models.URLField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='divination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divination',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
