# Generated by Django 4.0.3 on 2022-03-28 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runes', '0004_rt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rt',
            name='rune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rts', to='runes.rune'),
        ),
    ]
