# Generated by Django 4.0.3 on 2022-03-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runes', '0005_rune_divination_created_at_divination_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rune',
            name='order',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
