# Generated by Django 4.0.3 on 2022-03-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runes', '0006_rune_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rune',
            name='img_direct',
            field=models.URLField(null=True),
        ),
    ]
