# Generated by Django 4.0.3 on 2022-03-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runes', '0007_alter_runetranslation_rune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runetranslation',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
