# Generated by Django 4.0.3 on 2022-03-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runes', '0008_alter_runetranslation_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rune',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rune',
            name='forecast_meaning_direct',
        ),
        migrations.RemoveField(
            model_name='rune',
            name='forecast_meaning_inverted',
        ),
        migrations.RemoveField(
            model_name='rune',
            name='title',
        ),
    ]
