# Generated by Django 4.0.3 on 2022-03-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runes', '0009_remove_rune_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rune',
            name='title',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
