# Generated by Django 4.0.3 on 2022-04-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runes', '0010_rune_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nnn', models.CharField(max_length=100)),
            ],
        ),
    ]
