# Generated by Django 4.0.3 on 2022-03-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runes', '0010_alter_question_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='question',
            name='origin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='referer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
