# Generated by Django 4.0.3 on 2022-04-01 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runes', '0011_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
