# Generated by Django 4.0.3 on 2022-04-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runes', '0012_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.JSONField(null=True),
        ),
    ]
